// Tests for 11-dom-read. You do not edit this file.
// Run them with: npm test 11
//
// These load the real exercise.html into a pretend browser, hand your code a
// `document` exactly like the real one, and then call your functions.
import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const here = path.dirname(fileURLToPath(import.meta.url));
const html = readFileSync(path.join(here, "exercise.html"), "utf8");

// Set up the page BEFORE importing your file, so that `document` exists by the
// time your code runs.
const dom = new JSDOM(html);
globalThis.window = dom.window;
globalThis.document = dom.window.document;

const pristine = dom.window.document.body.innerHTML;

let exercise = null;
let loadError = null;
try {
  exercise = await import("./exercise.js");
} catch (error) {
  loadError = error;
}

function get(name) {
  if (loadError) {
    throw new Error(
      `exercise.js could not be loaded.\n        ${loadError.message}`
    );
  }
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

// Put the page back between tests, so one test cannot affect the next.
beforeEach(() => {
  dom.window.document.body.innerHTML = pristine;
});

describe("pageHeading", () => {
  it("returns the text of the h1", () => {
    expect(get("pageHeading")()).toBe("My Campus Store");
  });

  it("returns the text, not the element", () => {
    expect(get("pageHeading")()).toBeTypeOf("string");
  });
});

describe("productCount", () => {
  it("counts the five cards on the page", () => {
    expect(get("productCount")()).toBe(5);
  });

  it("returns a number", () => {
    expect(get("productCount")()).toBeTypeOf("number");
  });

  it("counts what is on the page, rather than a number you typed", () => {
    document.querySelector(".card").remove();
    expect(get("productCount")()).toBe(4);
  });
});

describe("productNames", () => {
  it("lists every name, in the order they appear", () => {
    expect(get("productNames")()).toEqual([
      "Notebook",
      "Backpack",
      "Pen",
      "Desk lamp",
      "Calculator",
    ]);
  });

  it("returns a real array, not a NodeList", () => {
    expect(Array.isArray(get("productNames")())).toBe(true);
  });

  it("reads the page rather than a list you typed out", () => {
    document.querySelector(".card h3").textContent = "Sketchpad";
    expect(get("productNames")()[0]).toBe("Sketchpad");
  });
});

describe("priceOf", () => {
  it("finds the price of the Pen", () => {
    expect(get("priceOf")("Pen")).toBe("15 EGP");
  });

  it("finds the price of the Desk lamp", () => {
    expect(get("priceOf")("Desk lamp")).toBe("180 EGP");
  });

  it("returns null when there is no card with that name", () => {
    expect(get("priceOf")("Nothing")).toBeNull();
  });

  it("does not crash on a name that is not there", () => {
    expect(() => get("priceOf")("Nothing")).not.toThrow();
  });
});

describe("soldOutNames", () => {
  it("exists, and is exported", () => {
    expect(get("soldOutNames")).toBeTypeOf("function");
  });

  it("lists the names on the sold-out cards", () => {
    expect(get("soldOutNames")()).toEqual(["Backpack", "Calculator"]);
  });

  it("leaves out the cards that are still for sale", () => {
    expect(get("soldOutNames")()).not.toContain("Notebook");
  });

  it("reads the classes rather than a list you typed out", () => {
    document.querySelectorAll(".card")[0].classList.add("sold-out");
    expect(get("soldOutNames")()).toEqual(["Notebook", "Backpack", "Calculator"]);
  });

  it("returns an empty array when nothing is sold out", () => {
    for (const card of document.querySelectorAll(".sold-out")) {
      card.classList.remove("sold-out");
    }
    expect(get("soldOutNames")()).toEqual([]);
  });
});
