// Tests for 08-async. You do not edit this file.
// Run them with: npm test 08
import { describe, it, expect } from "vitest";
import * as exercise from "./exercise.js";

function get(name) {
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

describe("productName", () => {
  it("finds the name of product 1", async () => {
    await expect(get("productName")(1)).resolves.toBe("Notebook");
  });

  it("finds the name of product 4", async () => {
    await expect(get("productName")(4)).resolves.toBe("Desk lamp");
  });

  it("gives back the name itself, not the whole product", async () => {
    // Forgetting `await` inside usually shows up here, as undefined.
    await expect(get("productName")(1)).resolves.toBeTypeOf("string");
  });
});

describe("priceLabel", () => {
  it("labels product 1 at 45 EGP", async () => {
    await expect(get("priceLabel")(1)).resolves.toBe("Notebook costs 45 EGP");
  });

  it("labels product 2 at 320 EGP", async () => {
    await expect(get("priceLabel")(2)).resolves.toBe("Backpack costs 320 EGP");
  });

  it("does not leave [object Promise] in the string", async () => {
    const label = await get("priceLabel")(1);
    expect(label).not.toContain("object Promise");
    expect(label).not.toContain("undefined");
  });
});

describe("safeProductName", () => {
  it("returns the name when the product exists", async () => {
    await expect(get("safeProductName")(3)).resolves.toBe("Pen");
  });

  it("returns 'Not found' for an id that does not exist", async () => {
    await expect(get("safeProductName")(99)).resolves.toBe("Not found");
  });

  it("does not let the failure escape", async () => {
    // Without a try/catch this rejects instead of resolving, and this is the
    // test that says so.
    await expect(get("safeProductName")(99)).resolves.toBeTypeOf("string");
  });
});

describe("namesInStock", () => {
  it("exists, and is exported", () => {
    expect(get("namesInStock")).toBeTypeOf("function");
  });

  it("returns a promise, because it is async", () => {
    expect(get("namesInStock")()).toBeInstanceOf(Promise);
  });

  it("lists the names of the products that are in stock", async () => {
    await expect(get("namesInStock")()).resolves.toEqual([
      "Notebook",
      "Pen",
      "Desk lamp",
    ]);
  });

  it("returns names, not whole products", async () => {
    const names = await get("namesInStock")();
    expect(names.every((name) => typeof name === "string")).toBe(true);
  });
});
