// Tests for 00-setup. You do not edit this file.
// Run them with: npm test 00
import { describe, it, expect } from "vitest";
import { getStudent } from "./exercise.js";

const PLACEHOLDER = "REPLACE ME";

describe("getStudent", () => {
  it("returns an object", () => {
    const student = getStudent();
    expect(student).toBeTypeOf("object");
    expect(student).not.toBeNull();
  });

  it("has your name filled in, not the placeholder", () => {
    const { name } = getStudent();
    expect(name).toBeTypeOf("string");
    expect(name.trim()).not.toBe("");
    expect(name).not.toBe(PLACEHOLDER);
  });

  it("has your student ID as a string of digits", () => {
    const { studentId } = getStudent();
    expect(studentId).toBeTypeOf("string");
    expect(studentId).not.toBe(PLACEHOLDER);
    // Digits only, still written inside quotes. "1234 5678" and 12345678
    // both fail on purpose. The length range catches a half-typed ID.
    expect(studentId).toMatch(/^\d{4,12}$/);
  });

  it("has your GitHub username, not an email address", () => {
    const { githubUsername } = getStudent();
    expect(githubUsername).toBeTypeOf("string");
    expect(githubUsername).not.toBe(PLACEHOLDER);
    expect(githubUsername.trim()).not.toBe("");
    expect(githubUsername).not.toContain("@");
    expect(githubUsername).not.toContain(" ");
  });
});
