// Tests for 13-forms. You do not edit this file.
// Run them with: npm test 13
import { describe, it, expect, beforeEach, vi } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const here = path.dirname(fileURLToPath(import.meta.url));
const html = readFileSync(path.join(here, "exercise.html"), "utf8");

const dom = new JSDOM(html);
globalThis.window = dom.window;
globalThis.document = dom.window.document;
const { document } = dom.window;
const pristine = document.body.innerHTML;

// Your file keeps the list of items in a variable of its own. If every test
// shared one copy of the module, items added by one test would still be there
// in the next. So each test gets a FRESH copy — which also means you can keep
// your items in whatever kind of variable you like.
let exercise = null;
let loadError = null;

async function reload() {
  vi.resetModules(); // forget the previous copy, so its variables start over
  try {
    exercise = await import("./exercise.js");
    loadError = null;
  } catch (error) {
    exercise = null;
    loadError = error;
  }
}

function get(name) {
  if (loadError) {
    throw new Error(`exercise.js could not be loaded.\n        ${loadError.message}`);
  }
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

const cards = () => document.querySelectorAll("#list .card");
const names = () =>
  Array.from(document.querySelectorAll("#list .card h3")).map((h) => h.textContent);
const errorText = () => document.querySelector("#error").textContent.trim();

function type(name, price) {
  document.querySelector("#name").value = name;
  document.querySelector("#price").value = price;
}

function submit() {
  document
    .querySelector("#product-form")
    .dispatchEvent(new dom.window.Event("submit", { cancelable: true, bubbles: true }));
}

beforeEach(async () => {
  document.body.innerHTML = pristine;
  await reload();
});

describe("readForm", () => {
  it("reads both boxes", () => {
    type("Pen", "15");
    expect(get("readForm")()).toEqual({ name: "Pen", price: 15 });
  });

  it("gives the price back as a number, not a string", () => {
    type("Pen", "15");
    expect(get("readForm")().price).toBeTypeOf("number");
  });

  it("trims spaces off the name", () => {
    type("  Notebook  ", "45");
    expect(get("readForm")().name).toBe("Notebook");
  });

  it("gives 0 for an empty price box", () => {
    type("Pen", "");
    expect(get("readForm")().price).toBe(0);
  });
});

describe("clearForm", () => {
  it("empties both boxes", () => {
    type("Pen", "15");
    get("clearForm")();
    expect(document.querySelector("#name").value).toBe("");
    expect(document.querySelector("#price").value).toBe("");
  });
});

describe("renderList", () => {
  it("draws one card per item", () => {
    get("renderList")([
      { name: "Pen", price: 15 },
      { name: "Notebook", price: 45 },
    ]);
    expect(cards()).toHaveLength(2);
    expect(names()).toEqual(["Pen", "Notebook"]);
  });

  it("puts the price, followed by EGP, in a p with the class price", () => {
    get("renderList")([{ name: "Pen", price: 15 }]);
    expect(document.querySelector("#list .card p.price").textContent).toBe("15 EGP");
  });

  it("replaces the old cards instead of adding to them", () => {
    get("renderList")([{ name: "Pen", price: 15 }]);
    get("renderList")([{ name: "Notebook", price: 45 }]);
    expect(names()).toEqual(["Notebook"]);
  });

  it("empties the list when given an empty array", () => {
    get("renderList")([{ name: "Pen", price: 15 }]);
    get("renderList")([]);
    expect(cards()).toHaveLength(0);
  });
});

describe("wireForm", () => {
  it("exists, and is exported", () => {
    expect(get("wireForm")).toBeTypeOf("function");
  });

  it("stops the browser reloading the page", () => {
    get("wireForm")();
    type("Pen", "15");
    const event = new dom.window.Event("submit", { cancelable: true, bubbles: true });
    document.querySelector("#product-form").dispatchEvent(event);
    expect(
      event.defaultPrevented,
      "Call event.preventDefault() first, or the page reloads and your work is lost."
    ).toBe(true);
  });

  it("adds what was typed to the list", () => {
    get("wireForm")();
    type("Backpack", "320");
    submit();
    expect(names()).toEqual(["Backpack"]);
    expect(document.querySelector("#list .card p.price").textContent).toBe("320 EGP");
  });

  it("keeps the ones already added", () => {
    get("wireForm")();
    type("Pen", "15");
    submit();
    type("Notebook", "45");
    submit();
    expect(names()).toEqual(["Pen", "Notebook"]);
  });

  it("empties the boxes after adding", () => {
    get("wireForm")();
    type("Pen", "15");
    submit();
    expect(document.querySelector("#name").value).toBe("");
    expect(document.querySelector("#price").value).toBe("");
  });

  it("refuses an empty name, and says so", () => {
    get("wireForm")();
    type("", "15");
    submit();
    expect(cards()).toHaveLength(0);
    expect(errorText()).toBe("Give the product a name.");
  });

  it("refuses a name that is only spaces", () => {
    get("wireForm")();
    type("   ", "15");
    submit();
    expect(cards()).toHaveLength(0);
  });

  it("refuses an empty price, and says so", () => {
    get("wireForm")();
    type("Pen", "");
    submit();
    expect(cards()).toHaveLength(0);
    expect(errorText()).toBe("Give the product a price.");
  });

  it("refuses a price of zero or less, and says so", () => {
    get("wireForm")();
    type("Pen", "-5");
    submit();
    expect(cards()).toHaveLength(0);
    expect(errorText()).toBe("Give the product a price.");
  });

  it("clears the error once a good one is added", () => {
    get("wireForm")();
    type("", "15");
    submit();
    type("Pen", "15");
    submit();
    expect(errorText()).toBe("");
    expect(names()).toEqual(["Pen"]);
  });
});
