// Tests for 01-basics. You do not edit this file.
// Run them with: npm test 01
import { describe, it, expect } from "vitest";
import {
  describeValue,
  priceLabel,
  isExpensive,
  shippingCost,
  stockLabel,
} from "./exercise.js";

describe("describeValue", () => {
  it("says a number is a number", () => {
    expect(describeValue(45)).toBe("45 is a number");
  });

  it("says a string is a string", () => {
    expect(describeValue("Pen")).toBe("Pen is a string");
  });

  it("says a boolean is a boolean", () => {
    expect(describeValue(true)).toBe("true is a boolean");
  });
});

describe("priceLabel", () => {
  it("labels a notebook at 45 EGP", () => {
    expect(priceLabel("Notebook", 45)).toBe("Notebook costs 45 EGP");
  });

  it("uses both values it is given, in order", () => {
    expect(priceLabel("Backpack", 320)).toBe("Backpack costs 320 EGP");
  });
});

describe("isExpensive", () => {
  it("says 320 EGP is expensive", () => {
    expect(isExpensive(320)).toBe(true);
  });

  it("says 45 EGP is not expensive", () => {
    expect(isExpensive(45)).toBe(false);
  });

  it("says 100 EGP is not expensive, because it is not over 100", () => {
    expect(isExpensive(100)).toBe(false);
  });

  it("returns true or false, not a number or a string", () => {
    expect(isExpensive(320)).toBeTypeOf("boolean");
  });
});

describe("shippingCost", () => {
  it("ships free on an order over 500 EGP", () => {
    expect(shippingCost(600)).toBe(0);
  });

  it("charges 50 EGP on a small order", () => {
    expect(shippingCost(120)).toBe(50);
  });

  it("charges 50 EGP on an order of exactly 500, because that is not over 500", () => {
    expect(shippingCost(500)).toBe(50);
  });
});

describe("stockLabel", () => {
  it("says a count of 0 is out of stock", () => {
    expect(stockLabel(0)).toBe("Out of stock");
  });

  it("says a count of 4 is low stock", () => {
    expect(stockLabel(4)).toBe("Low stock");
  });

  it("says a count of 9 is still low stock", () => {
    expect(stockLabel(9)).toBe("Low stock");
  });

  it("says a count of 10 is in stock", () => {
    expect(stockLabel(10)).toBe("In stock");
  });

  it("says a large count is in stock", () => {
    expect(stockLabel(250)).toBe("In stock");
  });
});
