// Tests for 09-html. You do not edit this file.
// Run them with: npm test 09
//
// These read your exercise.html and look at its structure: which elements
// exist, how they are nested, and whether the files you linked to are really
// there. They do not look at colours or layout — that is your eyes' job, and
// module 10's.
import { describe, it, expect } from "vitest";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const here = path.dirname(fileURLToPath(import.meta.url));
const source = readFileSync(path.join(here, "exercise.html"), "utf8");
const { document } = new JSDOM(source).window;

// Resolves a href/src the way a browser would, relative to the page.
function linkedFileExists(value) {
  if (!value || /^https?:/i.test(value)) return false;
  return existsSync(path.join(here, value));
}

describe("the page's head", () => {
  it("still starts with a doctype", () => {
    expect(source.trim().toLowerCase()).toContain("<!doctype html>");
  });

  it("has the title 'My Campus Store'", () => {
    expect(document.title.trim()).toBe("My Campus Store");
  });

  it("links the stylesheet", () => {
    const link = document.querySelector('link[rel="stylesheet"]');
    expect(link, "Add a <link rel=\"stylesheet\" href=\"...\"> in the head.").not.toBeNull();
  });

  it("links a stylesheet file that actually exists", () => {
    const href = document.querySelector('link[rel="stylesheet"]')?.getAttribute("href");
    expect(
      linkedFileExists(href),
      `The stylesheet href is "${href}", but there is no such file next to exercise.html. It should be styles.css.`
    ).toBe(true);
  });
});

describe("the page's structure", () => {
  it("has a header containing the h1", () => {
    const h1 = document.querySelector("h1");
    expect(h1, "The page needs an <h1>.").not.toBeNull();
    expect(
      h1.closest("header"),
      "The <h1> needs to be inside a <header> element."
    ).not.toBeNull();
  });

  it("has exactly one h1", () => {
    expect(document.querySelectorAll("h1")).toHaveLength(1);
  });

  it("has a main element", () => {
    expect(document.querySelector("main")).not.toBeNull();
  });

  it("has an h2 that says 'Items', inside the main", () => {
    const h2 = document.querySelector("main h2");
    expect(h2, "The <h2> needs to be inside <main>.").not.toBeNull();
    expect(h2.textContent.trim()).toBe("Items");
  });

  it("has a footer with a paragraph in it", () => {
    const footer = document.querySelector("footer");
    expect(footer, "The page needs a <footer>.").not.toBeNull();
    expect(
      footer.querySelector("p"),
      "The <footer> needs a <p> inside it."
    ).not.toBeNull();
  });
});

describe("the list", () => {
  it("has an unordered list inside the main", () => {
    expect(document.querySelector("main ul")).not.toBeNull();
  });

  it("has exactly three items in it", () => {
    const items = document.querySelectorAll("main ul > li");
    expect(items).toHaveLength(3);
  });

  it("has some text in each item", () => {
    for (const item of document.querySelectorAll("main ul > li")) {
      expect(item.textContent.trim()).not.toBe("");
    }
  });
});

describe("the price, the link and the image", () => {
  it("has a span with the class 'price'", () => {
    expect(document.querySelector("span.price")).not.toBeNull();
  });

  it("has some text inside that span", () => {
    expect(document.querySelector("span.price")?.textContent.trim()).not.toBe("");
  });

  it("has that span inside a paragraph", () => {
    expect(
      document.querySelector("span.price")?.closest("p"),
      "The <span class=\"price\"> belongs inside a <p>."
    ).not.toBeNull();
  });

  it("links to the GIU website with the text 'GIU'", () => {
    const link = document.querySelector('a[href*="giu-uni.de"]');
    expect(link, "Add an <a> whose href is https://www.giu-uni.de").not.toBeNull();
    expect(link.textContent.trim()).toBe("GIU");
  });

  it("has an image with a src", () => {
    const img = document.querySelector("img");
    expect(img, "The page needs an <img>.").not.toBeNull();
    expect(img.getAttribute("src")?.trim()).toBeTruthy();
  });

  it("gives the image an alt that describes it", () => {
    const alt = document.querySelector("img")?.getAttribute("alt") ?? "";
    expect(
      alt.trim().length,
      "alt is read aloud to blind users. It needs real words, not one letter."
    ).toBeGreaterThan(3);
  });
});

describe("the script", () => {
  it("links a script", () => {
    expect(
      document.querySelector("script[src]"),
      'Add <script src="app.js"></script> at the end of the body.'
    ).not.toBeNull();
  });

  it("links a script file that actually exists", () => {
    const src = document.querySelector("script[src]")?.getAttribute("src");
    expect(
      linkedFileExists(src),
      `The script src is "${src}", but there is no such file next to exercise.html. It should be app.js.`
    ).toBe(true);
  });

  it("puts the script at the end of the body, after the content", () => {
    const script = document.querySelector("script[src]");
    const footer = document.querySelector("footer");
    expect(script, "The page needs a <script src>.").not.toBeNull();
    expect(footer, "The page needs a <footer>.").not.toBeNull();
    // compareDocumentPosition: 4 means "footer comes before script"
    const scriptIsAfterFooter = Boolean(
      footer.compareDocumentPosition(script) & 4
    );
    expect(
      scriptIsAfterFooter,
      "The <script> tag belongs after the page's content, at the end of the body."
    ).toBe(true);
  });
});
