// Tests for 07-npm. You do not edit this file.
// Run them with: npm test 07
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
// exercise.js imports dayjs at the top, so it cannot even load until you have
// installed it. Loading it this way turns that into a readable message on each
// test instead of one stack trace and no results at all.
let exercise = null;
let loadError = null;
try {
  exercise = await import("./exercise.js");
} catch (error) {
  loadError = error;
}

function loaded() {
  if (loadError) {
    throw new Error(
      "07-npm/exercise.js could not be loaded.\n" +
        "        The usual cause is step 1: run `npm install dayjs` from the\n" +
        "        repo's root folder, then try again.\n" +
        `        The original error was: ${loadError.message}`
    );
  }
  return exercise;
}

function get(name) {
  const fn = loaded()[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

// The repo's own package.json, which you changed by installing things.
const manifest = JSON.parse(
  readFileSync(new URL("../package.json", import.meta.url), "utf8")
);
const dependencies = manifest.dependencies ?? {};

describe("installing dayjs", () => {
  it("added dayjs to the dependencies in package.json", () => {
    expect(
      dependencies.dayjs,
      "Run `npm install dayjs` from the repo's root folder."
    ).toBeTypeOf("string");
  });
});

describe("formatDate", () => {
  it("writes 2026-03-15 as 15/03/2026", () => {
    expect(get("formatDate")("2026-03-15")).toBe("15/03/2026");
  });

  it("keeps the leading zero on a single-digit day", () => {
    expect(get("formatDate")("2026-03-05")).toBe("05/03/2026");
  });

  it("works for a date in another year", () => {
    expect(get("formatDate")("2019-11-30")).toBe("30/11/2019");
  });
});

describe("yearOf", () => {
  it("finds the year in 2026-03-15", () => {
    expect(get("yearOf")("2026-03-15")).toBe(2026);
  });

  it("returns a number, not a string", () => {
    expect(get("yearOf")("2026-03-15")).toBeTypeOf("number");
  });
});

describe("addDays", () => {
  it("exists, and is exported", () => {
    expect(get("addDays")).toBeTypeOf("function");
  });

  it("adds 14 days to 2026-03-15", () => {
    expect(get("addDays")("2026-03-15", 14)).toBe("2026-03-29");
  });

  it("changes nothing when adding 0 days", () => {
    expect(get("addDays")("2026-03-15", 0)).toBe("2026-03-15");
  });

  it("rolls over into the next year", () => {
    expect(get("addDays")("2026-12-30", 3)).toBe("2027-01-02");
  });
});

describe("the npm script you added — step 4 in the README", () => {
  const ADVICE =
    'Step 4: add  "example": "node 07-npm/example.js"  inside "scripts" in ' +
    "the package.json at the root of this repo.";

  it("has a script called 'example' in package.json", () => {
    expect(manifest.scripts?.example, ADVICE).toBeTypeOf("string");
  });

  it("points at this module's example file", () => {
    // Checked again here, so this test fails with advice rather than with a
    // complaint about undefined.
    expect(manifest.scripts?.example, ADVICE).toBeTypeOf("string");
    expect(manifest.scripts.example).toContain("07-npm/example.js");
  });
});

describe("the package you chose", () => {
  it("has a name in myPackage", () => {
    expect(loaded().myPackage).toBeTypeOf("string");
    expect(loaded().myPackage).not.toBe("REPLACE ME");
    expect(loaded().myPackage.trim()).not.toBe("");
  });

  it("is not dayjs — this one is yours to pick", () => {
    expect(loaded().myPackage).not.toBe("dayjs");
  });

  it("is listed in package.json's dependencies", () => {
    expect(
      dependencies[loaded().myPackage],
      `package.json has no dependency called "${loaded().myPackage}". ` +
        `Run \`npm install ${loaded().myPackage}\` from the repo's root folder.`
    ).toBeTypeOf("string");
  });

  it("is really installed, and can be imported", async () => {
    // This is the check that a name typed by hand cannot pass.
    await expect(import(loaded().myPackage)).resolves.toBeTypeOf("object");
  });
});
