// Run this once, from the repo's root folder:
//
//     node checkpoint-a/generate.js
//
// It reads your GitHub username off this repo's git remote, turns it into a
// number, and writes YOUR version of the task into checkpoint-a/spec.md.
// Everyone's is different. Running it again gives you the same spec back.
import { writeFileSync, existsSync } from "node:fs";
import { getRemoteUrl, parseOwner, seedFromOwner } from "./lib/seed.js";
import { deriveSpec } from "./lib/spec.js";

const SPEC_PATH = new URL("./spec.md", import.meta.url);
const SOLUTION_PATH = new URL("./solution.js", import.meta.url);

let owner;
try {
  owner = parseOwner(getRemoteUrl());
} catch (error) {
  console.log("");
  console.log("Could not work out which GitHub account this repo belongs to.");
  console.log(`(${error.message})`);
  console.log("");
  console.log("This usually means one of:");
  console.log("  - you downloaded a ZIP instead of cloning your repo, or");
  console.log("  - you are not inside the repo folder.");
  console.log("");
  console.log("Fix: on GitHub use 'Use this template', then clone YOUR copy.");
  process.exit(1);
}

const seed = seedFromOwner(owner);
const spec = deriveSpec(seed);

// A made-up order, used only to show the wording. It is not in the data.
const sample = {
  id: 0,
  student: "Laila Hosny",
  city: "Aswan",
  item: "Stapler",
  quantity: 3,
  price: 70,
  status: "paid",
};

const fieldList = spec.fields.map((f) => `\`${f}\``).join(" and ");
const sampleJson = JSON.stringify([
  Object.fromEntries(spec.fields.map((f) => [f, sample[f]])),
]);

writeFileSync(
  SPEC_PATH,
  `# Checkpoint A — your task

Generated for GitHub account **${owner}**.
Do not edit this file. If you lose it, run \`node checkpoint-a/generate.js\` again.

This spec is yours. Someone else's answers will not pass your tests.

---

## What you are building

\`checkpoint-a/solution.js\`, exporting five functions. They read from
\`orders-db.js\`, which behaves exactly like module 08's fake database: it
answers after a short delay, and asking for an id that does not exist
**rejects**.

An order looks like this:

\`\`\`js
{ id: 7, student: "Laila Hosny", city: "Aswan", item: "Stapler",
  quantity: 3, price: 70, status: "paid" }
\`\`\`

\`price\` is the price of **one** item, in EGP.

---

## 1. \`loadOrders()\`

\`async\`. Returns every order from the database, as an array.

## 2. \`myOrders(orders)\`

Takes an array of orders. Returns only the ones that are **both**:

- from **${spec.city}**, and
- with status **${spec.status}**

Not async — it is given the list.

## 3. \`summarize(orders)\`

Takes an array of orders. Returns **${spec.summary.title}**, as a number.

> ${spec.summary.rule}

Not async.

## 4. \`describeOrder(id)\`

\`async\`. Looks up one order by its id and returns a label in exactly this
shape:

\`\`\`
${spec.label.shape}
\`\`\`

For the made-up order above, that would be:

\`\`\`
${spec.label.build(sample)}
\`\`\`

If there is **no order with that id**, the lookup rejects. Catch it and return
exactly:

\`\`\`
${spec.missing.shape}
\`\`\`

so that \`describeOrder(9999)\` returns \`"${spec.missing.build(9999)}"\`.
This function must never throw.

## 5. \`toJsonLines(orders)\`

Takes an array of orders. Returns **JSON text** for an array of objects
keeping only ${fieldList} from each order, in that order, and nothing else.

For a list holding only the made-up order above:

\`\`\`
${sampleJson}
\`\`\`

Plain \`JSON.stringify\` output — no indenting.

---

## When you are done

\`\`\`bash
npm test a
\`\`\`

Then commit **both** \`spec.md\` and \`solution.js\`:

\`\`\`bash
git add checkpoint-a/spec.md checkpoint-a/solution.js
git commit -m "Checkpoint A"
git push
\`\`\`
`,
  "utf8"
);

if (!existsSync(SOLUTION_PATH)) {
  writeFileSync(
    SOLUTION_PATH,
    `// Checkpoint A — your work goes in this file.
//
// Read checkpoint-a/spec.md. It was written for your GitHub account and it is
// the only description of the task that matters.
//
// Check your work with:  npm test a

import { findAllOrders, findOrderById } from "./orders-db.js";

// TODO: export the five functions spec.md asks for:
//   loadOrders()        async
//   myOrders(orders)
//   summarize(orders)
//   describeOrder(id)   async, and must never throw
//   toJsonLines(orders)
//
// Nothing is started for you this time. Everything you need is in modules
// 00 to 08.
`,
    "utf8"
  );
  console.log("Created checkpoint-a/solution.js");
} else {
  console.log("checkpoint-a/solution.js already exists — left it alone.");
}

console.log("");
console.log(`Spec generated for GitHub account: ${owner}`);
console.log("Written to: checkpoint-a/spec.md");
console.log("");
console.log("Read it, then write checkpoint-a/solution.js.");
console.log("Check your work with:  npm test a");
