// The checkpoint's data source. You do not edit this file.
//
// It behaves like the fake database from module 08: it answers after a short
// delay, and looking up an id that does not exist REJECTS.
//
// Every order looks like this:
//   { id, student, city, item, quantity, price, status }
// Prices are in EGP and are the price of ONE item.

const orders = [
  { id: 1, student: "Mariam Khalid", city: "Cairo", item: "Notebook", quantity: 2, price: 45, status: "paid" },
  { id: 2, student: "Youssef Amin", city: "Cairo", item: "Backpack", quantity: 1, price: 320, status: "paid" },
  { id: 3, student: "Ahmed Mansour", city: "Cairo", item: "Pen", quantity: 4, price: 15, status: "paid" },
  { id: 4, student: "Karim Saad", city: "Cairo", item: "Desk lamp", quantity: 3, price: 180, status: "pending" },
  { id: 5, student: "Dina Sherif", city: "Cairo", item: "Calculator", quantity: 2, price: 100, status: "pending" },
  { id: 6, student: "Omar Fathy", city: "Cairo", item: "Water bottle", quantity: 1, price: 60, status: "pending" },
  { id: 7, student: "Farida Nabil", city: "Cairo", item: "Folder", quantity: 4, price: 25, status: "cancelled" },
  { id: 8, student: "Nour Hassan", city: "Cairo", item: "Headphones", quantity: 3, price: 450, status: "cancelled" },
  { id: 9, student: "Habiba Tarek", city: "Cairo", item: "Mouse", quantity: 2, price: 210, status: "cancelled" },
  { id: 10, student: "Salma Ahmed", city: "Alexandria", item: "USB drive", quantity: 1, price: 130, status: "paid" },
  { id: 11, student: "Yasmin Adel", city: "Alexandria", item: "Ruler", quantity: 4, price: 10, status: "paid" },
  { id: 12, student: "Mostafa Zaki", city: "Alexandria", item: "Sketchpad", quantity: 3, price: 75, status: "paid" },
  { id: 13, student: "Mariam Khalid", city: "Alexandria", item: "Notebook", quantity: 2, price: 45, status: "pending" },
  { id: 14, student: "Youssef Amin", city: "Alexandria", item: "Backpack", quantity: 1, price: 320, status: "pending" },
  { id: 15, student: "Ahmed Mansour", city: "Alexandria", item: "Pen", quantity: 4, price: 15, status: "pending" },
  { id: 16, student: "Karim Saad", city: "Alexandria", item: "Desk lamp", quantity: 3, price: 180, status: "cancelled" },
  { id: 17, student: "Dina Sherif", city: "Alexandria", item: "Calculator", quantity: 2, price: 100, status: "cancelled" },
  { id: 18, student: "Omar Fathy", city: "Alexandria", item: "Water bottle", quantity: 1, price: 60, status: "cancelled" },
  { id: 19, student: "Farida Nabil", city: "Giza", item: "Folder", quantity: 4, price: 25, status: "paid" },
  { id: 20, student: "Nour Hassan", city: "Giza", item: "Headphones", quantity: 3, price: 450, status: "paid" },
  { id: 21, student: "Habiba Tarek", city: "Giza", item: "Mouse", quantity: 2, price: 210, status: "paid" },
  { id: 22, student: "Salma Ahmed", city: "Giza", item: "USB drive", quantity: 1, price: 130, status: "pending" },
  { id: 23, student: "Yasmin Adel", city: "Giza", item: "Ruler", quantity: 4, price: 10, status: "pending" },
  { id: 24, student: "Mostafa Zaki", city: "Giza", item: "Sketchpad", quantity: 3, price: 75, status: "pending" },
  { id: 25, student: "Mariam Khalid", city: "Giza", item: "Notebook", quantity: 2, price: 45, status: "cancelled" },
  { id: 26, student: "Youssef Amin", city: "Giza", item: "Backpack", quantity: 1, price: 320, status: "cancelled" },
  { id: 27, student: "Ahmed Mansour", city: "Giza", item: "Pen", quantity: 4, price: 15, status: "cancelled" },
  { id: 28, student: "Karim Saad", city: "Mansoura", item: "Desk lamp", quantity: 3, price: 180, status: "paid" },
  { id: 29, student: "Dina Sherif", city: "Mansoura", item: "Calculator", quantity: 2, price: 100, status: "paid" },
  { id: 30, student: "Omar Fathy", city: "Mansoura", item: "Water bottle", quantity: 1, price: 60, status: "paid" },
  { id: 31, student: "Farida Nabil", city: "Mansoura", item: "Folder", quantity: 4, price: 25, status: "pending" },
  { id: 32, student: "Nour Hassan", city: "Mansoura", item: "Headphones", quantity: 3, price: 450, status: "pending" },
  { id: 33, student: "Habiba Tarek", city: "Mansoura", item: "Mouse", quantity: 2, price: 210, status: "pending" },
  { id: 34, student: "Salma Ahmed", city: "Mansoura", item: "USB drive", quantity: 1, price: 130, status: "cancelled" },
  { id: 35, student: "Yasmin Adel", city: "Mansoura", item: "Ruler", quantity: 4, price: 10, status: "cancelled" },
  { id: 36, student: "Mostafa Zaki", city: "Mansoura", item: "Sketchpad", quantity: 3, price: 75, status: "cancelled" },
];

export function findAllOrders() {
  return new Promise((resolve) => {
    setTimeout(() => resolve(orders.map((order) => ({ ...order }))), 20);
  });
}

export function findOrderById(id) {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      const order = orders.find((o) => o.id === id);
      if (order) {
        resolve({ ...order });
      } else {
        reject(new Error(`No order with id ${id}`));
      }
    }, 20);
  });
}
