// Tests for Checkpoint A. You do not edit this file.
// Run them with: npm test a
//
// These tests work out YOUR spec the same way generate.js did — from your
// GitHub username — and then check your solution against it. They compute the
// right answers from orders-db.js directly, so they do not depend on your code
// being written any particular way.
import { describe, it, expect } from "vitest";
import { existsSync } from "node:fs";
import { seedForThisRepo } from "./lib/seed.js";
import { deriveSpec, expectedMyOrders, expectedJson } from "./lib/spec.js";
import { findAllOrders } from "./orders-db.js";

const SPEC_PATH = new URL("./spec.md", import.meta.url);

let spec = null;
let specError = null;
try {
  spec = deriveSpec(seedForThisRepo());
} catch (error) {
  specError = error;
}

let solution = null;
let loadError = null;
try {
  solution = await import("./solution.js");
} catch (error) {
  loadError = error;
}

function mySpec() {
  if (specError) {
    throw new Error(
      "Could not work out your spec from this repo's git remote.\n" +
        "        Run: node checkpoint-a/generate.js   — it explains what is wrong.\n" +
        `        The original error was: ${specError.message}`
    );
  }
  return spec;
}

function get(name) {
  if (loadError) {
    throw new Error(
      "checkpoint-a/solution.js could not be loaded.\n" +
        "        Have you run `node checkpoint-a/generate.js` yet?\n" +
        `        The original error was: ${loadError.message}`
    );
  }
  const fn = solution[name];
  if (typeof fn !== "function") {
    throw new Error(
      `solution.js does not export a function called "${name}" yet.\n` +
        `        See checkpoint-a/spec.md, and remember the word "export".`
    );
  }
  return fn;
}

const allOrders = await findAllOrders();

describe("setup", () => {
  it("has a generated spec.md, which means you ran generate.js", () => {
    expect(
      existsSync(SPEC_PATH),
      "Run: node checkpoint-a/generate.js"
    ).toBe(true);
  });

  it("worked out which GitHub account this repo belongs to", () => {
    expect(mySpec().city).toBeTypeOf("string");
  });
});

describe("loadOrders", () => {
  it("is async, so it returns a promise", () => {
    expect(get("loadOrders")()).toBeInstanceOf(Promise);
  });

  it("returns every order in the database", async () => {
    await expect(get("loadOrders")()).resolves.toHaveLength(allOrders.length);
  });

  it("returns the orders themselves, not just their ids", async () => {
    const orders = await get("loadOrders")();
    expect(orders[0]).toHaveProperty("student");
    expect(orders[0]).toHaveProperty("price");
  });
});

describe("myOrders", () => {
  it("keeps only the orders from your city with your status", () => {
    const expected = expectedMyOrders(allOrders, mySpec());
    expect(get("myOrders")(allOrders)).toEqual(expected);
  });

  it("keeps every order that matches, and finds some", () => {
    const expected = expectedMyOrders(allOrders, mySpec());
    const kept = get("myOrders")(allOrders);
    // Guarded, so that returning an empty list cannot pass this by accident.
    expect(expected.length).toBeGreaterThan(0);
    expect(kept).toHaveLength(expected.length);
  });

  it("keeps nothing that fails either half of the test", () => {
    const { city, status } = mySpec();
    const kept = get("myOrders")(allOrders);
    expect(kept.length).toBeGreaterThan(0);
    for (const order of kept) {
      expect(order.city).toBe(city);
      expect(order.status).toBe(status);
    }
  });

  it("returns an empty list when nothing matches", () => {
    expect(get("myOrders")([])).toEqual([]);
  });
});

describe("summarize", () => {
  it("summarizes your own filtered orders the way your spec asks", () => {
    const mine = expectedMyOrders(allOrders, mySpec());
    expect(get("summarize")(mine)).toBe(mySpec().summary.compute(mine));
  });

  it("summarizes the whole list the same way", () => {
    expect(get("summarize")(allOrders)).toBe(
      mySpec().summary.compute(allOrders)
    );
  });

  it("returns a number", () => {
    expect(get("summarize")(allOrders)).toBeTypeOf("number");
  });

  it("returns 0 for an empty list", () => {
    expect(get("summarize")([])).toBe(0);
  });
});

describe("describeOrder", () => {
  it("describes order 1 in the shape your spec gives", async () => {
    const order = allOrders.find((o) => o.id === 1);
    await expect(get("describeOrder")(1)).resolves.toBe(mySpec().label.build(order));
  });

  it("describes a different order correctly too", async () => {
    const order = allOrders.find((o) => o.id === 23);
    await expect(get("describeOrder")(23)).resolves.toBe(mySpec().label.build(order));
  });

  it("returns your not-found wording for an id that does not exist", async () => {
    await expect(get("describeOrder")(9999)).resolves.toBe(
      mySpec().missing.build(9999)
    );
  });

  it("never throws, even for a missing order", async () => {
    // Without a try/catch this rejects instead of resolving.
    await expect(get("describeOrder")(4242)).resolves.toBeTypeOf("string");
  });
});

describe("toJsonLines", () => {
  it("returns a string, not an array", () => {
    expect(get("toJsonLines")(allOrders)).toBeTypeOf("string");
  });

  it("keeps only the fields your spec asks for", () => {
    expect(get("toJsonLines")(allOrders)).toBe(expectedJson(allOrders, mySpec()));
  });

  it("works on your filtered orders too", () => {
    const mine = expectedMyOrders(allOrders, mySpec());
    expect(get("toJsonLines")(mine)).toBe(expectedJson(mine, mySpec()));
  });

  it("returns [] for an empty list", () => {
    expect(get("toJsonLines")([])).toBe("[]");
  });
});
