// Run this once, from the repo's root folder:
//
//     node checkpoint-b/generate.js
//
// It reads your GitHub username off this repo's git remote and writes YOUR
// version of the task into checkpoint-b/spec.md. Everyone's is different.
// Running it again gives you the same spec back, and never overwrites work.
import { writeFileSync, existsSync } from "node:fs";
import { getRemoteUrl, parseOwner, seedFromOwner } from "./lib/seed.js";
import { deriveSpec } from "./lib/spec.js";

const files = {
  spec: new URL("./spec.md", import.meta.url),
  html: new URL("./page.html", import.meta.url),
  css: new URL("./page.css", import.meta.url),
  js: new URL("./page.js", import.meta.url),
};

let owner;
try {
  owner = parseOwner(getRemoteUrl());
} catch (error) {
  console.log("");
  console.log("Could not work out which GitHub account this repo belongs to.");
  console.log(`(${error.message})`);
  console.log("");
  console.log("Fix: on GitHub use 'Use this template', then clone YOUR copy.");
  process.exit(1);
}

const spec = deriveSpec(seedFromOwner(owner));
const { heading, itemClass, filter, button, itemText } = spec;

writeFileSync(
  files.spec,
  `# Checkpoint B — your task

Generated for GitHub account **${owner}**.
Do not edit this file. If you lose it, run \`node checkpoint-b/generate.js\` again.

This spec is yours. Someone else's answers will not pass your tests.

---

## What you are building

A small page, in three files you write yourself:

| File | What it holds |
|---|---|
| \`checkpoint-b/page.html\` | the structure |
| \`checkpoint-b/page.css\` | the styling |
| \`checkpoint-b/page.js\` | the behaviour |

The data is given to you in \`checkpoint-b/items.js\`, which you import. Do not
edit it, and do not copy the items into your own files.

\`\`\`js
import { items } from "./items.js";
\`\`\`

Every item looks like:

\`\`\`js
{ id: 1, name: "Notebook", category: "stationery", price: 45, inStock: true }
\`\`\`

---

## 1. \`page.html\`

- A \`<!DOCTYPE html>\` and a \`<html lang="en">\`.
- In the head: a \`<meta charset="UTF-8">\`, a \`<title>\` — any text you like —
  and a \`<link>\` to your \`page.css\`.
- An \`<h1>\` whose text is exactly:

  \`\`\`
  ${heading}
  \`\`\`

- A \`<ul>\` or \`<ol>\` with \`id="list"\`. **Leave it empty** — JavaScript fills it.
- A \`<button>\` with \`id="${button.id}"\` whose text is exactly:

  \`\`\`
  ${button.label}
  \`\`\`

- A \`<script>\` that loads your \`page.js\`. Because \`page.js\` uses \`import\`,
  the tag needs \`type="module"\`:

  \`\`\`html
  <script type="module" src="page.js"></script>
  \`\`\`

## 2. \`page.css\`

- A rule for \`body\` that sets a \`font-family\` and a \`background-color\`.
- A rule for \`.${itemClass}\` — the class your list items carry — that sets
  \`padding\` and \`color\`.
- The text has to be **readable**: your \`.${itemClass}\` colour needs a contrast
  of at least 3:1 against the background behind it. The tests check this.

## 3. \`page.js\`

Export three functions.

### \`renderItems(list)\`

Draws an array of items into \`#list\`, replacing whatever was there.
Each item becomes an \`<li>\` with:

- the class \`${itemClass}\`, and
- its text in exactly this shape:

  \`\`\`
  ${itemText.shape}
  \`\`\`

  so the Notebook (45 EGP, stationery) comes out as:

  \`\`\`
  ${itemText.example}
  \`\`\`

Called again with a different array, it replaces the old items rather than
adding to them. An empty array leaves the list empty.

### \`matching()\`

Returns ${filter.title}, as an array of item objects from \`items\`.

> ${filter.rule}

### \`start()\`

Sets the page up:

1. Draws **all** the items straight away, using \`renderItems\`.
2. Listens for a click on \`#${button.id}\`. When it is clicked, the list is
   redrawn with ${filter.title}.

---

## When you are done

\`\`\`bash
npm run open b        # look at it
npm test b            # check it
\`\`\`

Then commit **all four** files:

\`\`\`bash
git add checkpoint-b/spec.md checkpoint-b/page.html checkpoint-b/page.css checkpoint-b/page.js
git commit -m "Checkpoint B"
git push
\`\`\`
`,
  "utf8"
);

const starters = {
  html: `<!--
  Checkpoint B — your page. Build it to checkpoint-b/spec.md.
  Look at it with:  npm run open b
-->
`,
  css: `/* Checkpoint B — your styling. Build it to checkpoint-b/spec.md. */
`,
  js: `// Checkpoint B — your behaviour. Build it to checkpoint-b/spec.md.
//
// The data is given to you:
import { items } from "./items.js";

// Export renderItems(list), matching() and start(), as the spec describes.
// Nothing is started for you. Everything you need is in modules 00 to 13.
`,
};

for (const [key, contents] of Object.entries(starters)) {
  if (!existsSync(files[key])) {
    writeFileSync(files[key], contents, "utf8");
    console.log(`Created checkpoint-b/page.${key}`);
  } else {
    console.log(`checkpoint-b/page.${key} already exists — left it alone.`);
  }
}

console.log("");
console.log(`Spec generated for GitHub account: ${owner}`);
console.log("Written to: checkpoint-b/spec.md");
console.log("");
console.log("Read it, then build the three page files.");
console.log("Look at it with:  npm run open b");
console.log("Check it with:    npm test b");
