// The checkpoint's data. You do not edit this file — you import it.
//
// Every item looks like:
//   { id, name, category, price, inStock }
// Prices are in EGP.

export const items = [
  { id: 1, name: "Notebook", category: "stationery", price: 45, inStock: true },
  { id: 2, name: "Backpack", category: "bags", price: 320, inStock: false },
  { id: 3, name: "Pen", category: "stationery", price: 15, inStock: true },
  { id: 4, name: "Desk lamp", category: "electronics", price: 180, inStock: true },
  { id: 5, name: "Calculator", category: "electronics", price: 100, inStock: false },
  { id: 6, name: "Water bottle", category: "kitchen", price: 60, inStock: true },
  { id: 7, name: "Folder", category: "stationery", price: 25, inStock: true },
  { id: 8, name: "Headphones", category: "electronics", price: 450, inStock: true },
  { id: 9, name: "Lunch box", category: "kitchen", price: 90, inStock: false },
  { id: 10, name: "Tote bag", category: "bags", price: 70, inStock: true },
  { id: 11, name: "Ruler", category: "stationery", price: 10, inStock: true },
  { id: 12, name: "Travel mug", category: "kitchen", price: 130, inStock: true },
];
