// Tests for Checkpoint B. You do not edit this file.
// Run them with: npm test b
//
// These work out YOUR spec the same way generate.js did — from your GitHub
// username — and check your three page files against it.
import { describe, it, expect, beforeEach, vi } from "vitest";
import { existsSync, readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";
import { seedForThisRepo } from "./lib/seed.js";
import {
  deriveSpec,
  expectedAll,
  expectedFiltered,
  expectedMatchingNames,
} from "./lib/spec.js";

const here = path.dirname(fileURLToPath(import.meta.url));
const file = (name) => path.join(here, name);

let spec = null;
let specError = null;
try {
  spec = deriveSpec(seedForThisRepo());
} catch (error) {
  specError = error;
}

function mySpec() {
  if (specError) {
    throw new Error(
      "Could not work out your spec from this repo's git remote.\n" +
        "        Run: node checkpoint-b/generate.js   — it explains what is wrong.\n" +
        `        The original error was: ${specError.message}`
    );
  }
  return spec;
}

function readOrFail(name) {
  if (!existsSync(file(name))) {
    throw new Error(
      `checkpoint-b/${name} does not exist yet.\n` +
        "        Run: node checkpoint-b/generate.js   then build it to spec.md."
    );
  }
  return readFileSync(file(name), "utf8");
}

// --- the page, parsed ------------------------------------------------------
function buildDom() {
  const html = readOrFail("page.html");
  const css = existsSync(file("page.css")) ? readFileSync(file("page.css"), "utf8") : "";
  // Swap the stylesheet link for the real CSS so colours can be computed.
  const withCss = html.replace(/<link[^>]*rel=["']stylesheet["'][^>]*>/i, `<style>${css}</style>`);
  return new JSDOM(withCss.includes("<style>") ? withCss : withCss.replace("</head>", `<style>${css}</style></head>`));
}

// --- your page.js, loaded against a fresh page -----------------------------
let page = null;
let loadError = null;
let dom = null;

async function reload() {
  dom = buildDom();
  globalThis.window = dom.window;
  globalThis.document = dom.window.document;
  vi.resetModules();
  try {
    page = await import("./page.js");
    loadError = null;
  } catch (error) {
    page = null;
    loadError = error;
  }
}

function get(name) {
  if (loadError) {
    throw new Error(
      `checkpoint-b/page.js could not be loaded.\n        ${loadError.message}`
    );
  }
  const fn = page?.[name];
  if (typeof fn !== "function") {
    throw new Error(
      `page.js does not export a function called "${name}" yet.\n` +
        `        See checkpoint-b/spec.md, and remember the word "export".`
    );
  }
  return fn;
}

const listNames = () =>
  Array.from(dom.window.document.querySelectorAll("#list > li")).map((li) =>
    li.textContent.trim()
  );

beforeEach(async () => {
  await reload();
});

describe("setup", () => {
  it("has a generated spec.md, which means you ran generate.js", () => {
    expect(existsSync(file("spec.md")), "Run: node checkpoint-b/generate.js").toBe(true);
  });

  it("has all three page files", () => {
    for (const name of ["page.html", "page.css", "page.js"]) {
      expect(existsSync(file(name)), `checkpoint-b/${name} is missing.`).toBe(true);
    }
  });
});

describe("page.html", () => {
  it("starts with a doctype", () => {
    expect(readOrFail("page.html").trim().toLowerCase()).toContain("<!doctype html>");
  });

  it("declares its character set", () => {
    expect(dom.window.document.querySelector("meta[charset]")).not.toBeNull();
  });

  it("has a title", () => {
    expect(dom.window.document.title.trim()).not.toBe("");
  });

  it("has the h1 your spec asks for", () => {
    const h1 = dom.window.document.querySelector("h1");
    expect(h1, "The page needs an <h1>.").not.toBeNull();
    expect(h1.textContent.trim()).toBe(mySpec().heading);
  });

  it("has an empty list with id 'list'", () => {
    const list = dom.window.document.querySelector("#list");
    expect(list, "The page needs a <ul id=\"list\"> or <ol id=\"list\">.").not.toBeNull();
    expect(["UL", "OL"]).toContain(list.tagName);
    expect(
      list.querySelectorAll("li"),
      "Leave #list empty in the HTML — page.js fills it."
    ).toHaveLength(0);
  });

  it("has the button your spec asks for", () => {
    const button = dom.window.document.querySelector(`#${mySpec().button.id}`);
    expect(button, `The page needs a button with id="${mySpec().button.id}".`).not.toBeNull();
    expect(button.tagName).toBe("BUTTON");
    expect(button.textContent.trim()).toBe(mySpec().button.label);
  });

  it("links a stylesheet and a module script", () => {
    const html = readOrFail("page.html");
    expect(/rel=["']stylesheet["']/i.test(html), "Link your page.css.").toBe(true);
    const script = /<script[^>]*src=["'][^"']*page\.js["'][^>]*>/i.exec(html)?.[0] ?? "";
    expect(script, "Add a <script> that loads page.js.").not.toBe("");
    expect(
      /type=["']module["']/i.test(script),
      'page.js uses import, so the tag needs type="module".'
    ).toBe(true);
  });
});

describe("page.css", () => {
  const rulesOf = (css) => [...new JSDOM(`<style>${css}</style>`).window.document.styleSheets[0].cssRules];
  const tidy = (s) => s.replace(/\s+/g, " ").trim().toLowerCase();

  function declarations(selector) {
    const css = readOrFail("page.css");
    const merged = {};
    for (const rule of rulesOf(css)) {
      if (tidy(rule.selectorText ?? "") === tidy(selector)) {
        for (const property of rule.style) {
          merged[property] = rule.style.getPropertyValue(property).trim();
        }
      }
    }
    return merged;
  }

  it("styles the body with a font and a background", () => {
    const body = declarations("body");
    expect(body["font-family"], "`body` needs a font-family.").toBeTruthy();
    expect(body["background-color"], "`body` needs a background-color.").toBeTruthy();
  });

  it("styles your item class with padding and a colour", () => {
    const item = declarations(`.${mySpec().itemClass}`);
    expect(
      item.padding,
      `\`.${mySpec().itemClass}\` needs padding.`
    ).toBeTruthy();
    expect(item.color, `\`.${mySpec().itemClass}\` needs a color.`).toBeTruthy();
  });
});

describe("renderItems", () => {
  const sample = [
    { id: 1, name: "Notebook", category: "stationery", price: 45, inStock: true },
    { id: 3, name: "Pen", category: "stationery", price: 15, inStock: true },
  ];

  it("draws one li per item, worded the way your spec asks", () => {
    get("renderItems")(sample);
    expect(listNames()).toEqual(sample.map((item) => mySpec().itemText.build(item)));
  });

  it("gives each one your item class", () => {
    get("renderItems")(sample);
    const li = dom.window.document.querySelector("#list > li");
    expect(
      li.classList.contains(mySpec().itemClass),
      `Each <li> needs the class "${mySpec().itemClass}".`
    ).toBe(true);
  });

  it("replaces the old items instead of adding to them", () => {
    get("renderItems")(sample);
    get("renderItems")([sample[1]]);
    expect(listNames()).toEqual([mySpec().itemText.build(sample[1])]);
  });

  it("empties the list when given an empty array", () => {
    get("renderItems")(sample);
    get("renderItems")([]);
    expect(listNames()).toEqual([]);
  });
});

describe("matching", () => {
  it("returns the items your spec asks for", () => {
    const names = get("matching")().map((item) => item.name);
    expect(names).toEqual(expectedMatchingNames(mySpec()));
  });

  it("returns item objects, not just their names", () => {
    const [first] = get("matching")();
    expect(first, "matching() found nothing at all.").toBeTruthy();
    expect(first).toHaveProperty("name");
    expect(first).toHaveProperty("price");
  });

  it("leaves some items out", () => {
    expect(get("matching")().length).toBeLessThan(expectedAll(mySpec()).length);
  });
});

describe("start", () => {
  it("draws every item straight away", () => {
    get("start")();
    expect(listNames()).toEqual(expectedAll(mySpec()));
  });

  it("redraws with only the matching ones when the button is clicked", () => {
    get("start")();
    dom.window.document.querySelector(`#${mySpec().button.id}`).click();
    expect(listNames()).toEqual(expectedFiltered(mySpec()));
  });

  it("waits for the click rather than filtering immediately", () => {
    get("start")();
    expect(
      listNames().length,
      "start() should show everything until the button is clicked."
    ).toBe(expectedAll(mySpec()).length);
  });
});

describe("is the text readable?", () => {
  const channel = (v) => {
    const c = v / 255;
    return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
  };
  const luminance = ([r, g, b]) =>
    0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
  const parseRgb = (value) => {
    const m = /rgba?\(\s*(\d+)[,\s]+(\d+)[,\s]+(\d+)/.exec(value ?? "");
    return m ? [Number(m[1]), Number(m[2]), Number(m[3])] : null;
  };

  it("the items can be read against what is behind them", () => {
    get("renderItems")([{ id: 1, name: "Notebook", category: "stationery", price: 45, inStock: true }]);
    const li = dom.window.document.querySelector("#list > li");
    if (!li) return;
    const front = parseRgb(dom.window.getComputedStyle(li).color);
    let node = li;
    let back = null;
    while (node && !back) {
      const value = dom.window.getComputedStyle(node).backgroundColor;
      const rgb = parseRgb(value);
      if (rgb && !/rgba\([^)]*,\s*0\s*\)/.test(value)) back = rgb;
      node = node.parentElement;
    }
    if (!front || !back) return;
    const a = luminance(front);
    const b = luminance(back);
    const [light, dark] = a > b ? [a, b] : [b, a];
    const ratio = (light + 0.05) / (dark + 0.05);
    expect(
      ratio,
      `Your item text is rgb(${front.join(", ")}) on rgb(${back.join(", ")}), ` +
        `a contrast of ${ratio.toFixed(2)}:1. Below 3:1 is very hard to read.`
    ).toBeGreaterThan(3);
  });
});
