// Tests for 03-objects. You do not edit this file.
// Run them with: npm test 03
import { describe, it, expect } from "vitest";
import {
  productName,
  getField,
  studentCity,
  summarize,
  withPrice,
} from "./exercise.js";

function makeProduct() {
  return { id: 1, name: "Notebook", price: 45, inStock: true };
}

function makeStudent() {
  return {
    name: "Salma",
    studentId: "19000123",
    address: { city: "Cairo", street: "El Tahrir" },
  };
}

describe("productName", () => {
  it("returns the name of the product", () => {
    expect(productName(makeProduct())).toBe("Notebook");
  });

  it("works for any product it is given", () => {
    expect(productName({ id: 2, name: "Backpack", price: 320 })).toBe("Backpack");
  });
});

describe("getField", () => {
  it("returns the price when asked for price", () => {
    expect(getField(makeProduct(), "price")).toBe(45);
  });

  it("returns the name when asked for name", () => {
    expect(getField(makeProduct(), "name")).toBe("Notebook");
  });

  it("returns undefined when there is no such key", () => {
    expect(getField(makeProduct(), "colour")).toBeUndefined();
  });

  it("looks up the key it is given, not a key called 'field'", () => {
    // A dot instead of brackets fails this one.
    expect(getField(makeProduct(), "inStock")).toBe(true);
  });
});

describe("studentCity", () => {
  it("returns the city from inside the address", () => {
    expect(studentCity(makeStudent())).toBe("Cairo");
  });

  it("works for a student in another city", () => {
    const student = makeStudent();
    student.address.city = "Alexandria";
    expect(studentCity(student)).toBe("Alexandria");
  });
});

describe("summarize", () => {
  it("summarizes a notebook at 45 EGP", () => {
    expect(summarize(makeProduct())).toBe("Notebook costs 45 EGP");
  });

  it("uses the product it is given", () => {
    expect(summarize({ id: 2, name: "Backpack", price: 320, inStock: false })).toBe(
      "Backpack costs 320 EGP"
    );
  });
});

describe("withPrice", () => {
  it("returns a product with the new price", () => {
    expect(withPrice(makeProduct(), 30)).toEqual({
      id: 1,
      name: "Notebook",
      price: 30,
      inStock: true,
    });
  });

  it("keeps every other key exactly as it was", () => {
    const updated = withPrice(makeProduct(), 30);
    expect(updated.id).toBe(1);
    expect(updated.name).toBe("Notebook");
    expect(updated.inStock).toBe(true);
  });

  it("leaves the original product alone", () => {
    const product = makeProduct();
    withPrice(product, 30);
    expect(product.price).toBe(45);
  });

  it("returns a new object, not the same one back", () => {
    const product = makeProduct();
    expect(withPrice(product, 30)).not.toBe(product);
  });
});
