// Tests for 02-functions. You do not edit this file.
// Run them with: npm test 02
import { describe, it, expect } from "vitest";

// Note: this file imports the whole exercise file at once, rather than naming
// each function. That is on purpose — the last two functions do not exist
// until you write them, and this way a missing one fails its own tests with a
// clear message instead of stopping the whole file.
import * as exercise from "./exercise.js";

function get(name) {
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

describe("greet", () => {
  it("greets Ahmed by name", () => {
    expect(get("greet")("Ahmed")).toBe("Hello, Ahmed!");
  });

  it("uses whatever name it is given", () => {
    expect(get("greet")("Salma")).toBe("Hello, Salma!");
  });

  it("returns the greeting instead of printing it", () => {
    // A function that only calls console.log gives back undefined.
    expect(get("greet")("Ahmed")).not.toBeUndefined();
  });
});

describe("double", () => {
  it("doubles 21 to 42", () => {
    expect(get("double")(21)).toBe(42);
  });

  it("doubles 0 to 0", () => {
    expect(get("double")(0)).toBe(0);
  });

  it("returns the number instead of forgetting to return it", () => {
    // Braces with no return inside hand back undefined.
    expect(get("double")(5)).not.toBeUndefined();
  });
});

describe("applyDiscount", () => {
  it("takes 25% off 320 EGP", () => {
    expect(get("applyDiscount")(320, 25)).toBe(240);
  });

  it("takes 10% off 200 EGP", () => {
    expect(get("applyDiscount")(200, 10)).toBe(180);
  });

  it("changes nothing when the discount is 0%", () => {
    expect(get("applyDiscount")(45, 0)).toBe(45);
  });

  it("returns a number, not a string", () => {
    expect(get("applyDiscount")(320, 25)).toBeTypeOf("number");
  });
});

describe("formatPrice", () => {
  it("exists, and is exported", () => {
    expect(get("formatPrice")).toBeTypeOf("function");
  });

  it("uses EGP when no currency is given", () => {
    expect(get("formatPrice")(45)).toBe("45 EGP");
  });

  it("uses the currency it is given", () => {
    expect(get("formatPrice")(45, "USD")).toBe("45 USD");
  });

  it("still defaults to EGP for a different amount", () => {
    expect(get("formatPrice")(320)).toBe("320 EGP");
  });
});

describe("applyTwice", () => {
  it("exists, and is exported", () => {
    expect(get("applyTwice")).toBeTypeOf("function");
  });

  it("doubles 5 twice, giving 20", () => {
    expect(get("applyTwice")(get("double"), 5)).toBe(20);
  });

  it("works with any function it is given", () => {
    const addTen = (n) => n + 10;
    expect(get("applyTwice")(addTen, 5)).toBe(25);
  });

  it("calls the function exactly twice", () => {
    let calls = 0;
    const count = (n) => {
      calls = calls + 1;
      return n;
    };
    get("applyTwice")(count, 1);
    expect(calls).toBe(2);
  });

  it("works on strings too, not just numbers", () => {
    const shout = (text) => `${text}!`;
    expect(get("applyTwice")(shout, "Hi")).toBe("Hi!!");
  });
});
