// Tests for 06-modules. You do not edit this file.
// Run them with: npm test 06
import { describe, it, expect } from "vitest";
import * as exercise from "./exercise.js";

function get(name) {
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

// discounts.js is the file YOU create, so it may not exist yet. Loading it
// this way means a missing file fails its own tests with a readable message
// instead of stopping the whole run.
async function loadDiscounts() {
  try {
    return await import("./discounts.js");
  } catch {
    throw new Error(
      "06-modules/discounts.js does not exist yet, or it has an error in it.\n" +
        "        Create the file next to exercise.js and export halfPrice from it."
    );
  }
}

describe("productCount", () => {
  it("counts the products in the catalog", () => {
    expect(get("productCount")()).toBe(4);
  });

  it("returns a number, not the list itself", () => {
    expect(get("productCount")()).toBeTypeOf("number");
  });
});

describe("priceTag", () => {
  it("tags a notebook at 45 EGP", () => {
    expect(get("priceTag")({ name: "Notebook", price: 45 })).toBe("45 EGP");
  });

  it("tags a backpack at 320 EGP", () => {
    expect(get("priceTag")({ name: "Backpack", price: 320 })).toBe("320 EGP");
  });
});

describe("shopHeading", () => {
  it("builds a heading from the shop's name", () => {
    expect(get("shopHeading")()).toBe("GIU Campus Store catalog");
  });

  it("uses the imported name rather than a typed-out copy", () => {
    // If the name were typed by hand, this would not be exactly right.
    expect(get("shopHeading")()).toContain("GIU Campus Store");
  });
});

describe("discounts.js — the file you create", () => {
  it("exists, next to exercise.js", async () => {
    await expect(loadDiscounts()).resolves.toBeTypeOf("object");
  });

  it("exports a named function called halfPrice", async () => {
    const discounts = await loadDiscounts();
    expect(discounts.halfPrice).toBeTypeOf("function");
  });

  it("halves 320 to 160", async () => {
    const { halfPrice } = await loadDiscounts();
    expect(halfPrice(320)).toBe(160);
  });

  it("halves 45 to 22.5", async () => {
    const { halfPrice } = await loadDiscounts();
    expect(halfPrice(45)).toBe(22.5);
  });

  it("has a default export, the string 'Winter sale'", async () => {
    const discounts = await loadDiscounts();
    expect(discounts.default).toBe("Winter sale");
  });
});
