// Tests for 04-arrays. You do not edit this file.
// Run them with: npm test 04
import { describe, it, expect } from "vitest";

// Note: this file imports the whole exercise file at once, rather than naming
// each function. That is on purpose — the last function does not exist until
// you write it, and this way a missing one fails its own tests with a clear
// message instead of stopping the whole file.
import * as exercise from "./exercise.js";

function get(name) {
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

// The tests use their own list, not the one in example.js.
// Each test starts from a fresh copy.
function makeProducts() {
  return [
    { id: 1, name: "Notebook", price: 45, inStock: true },
    { id: 2, name: "Backpack", price: 320, inStock: false },
    { id: 3, name: "Pen", price: 15, inStock: true },
    { id: 4, name: "Desk lamp", price: 180, inStock: true },
    { id: 5, name: "Calculator", price: 100, inStock: false },
  ];
}

describe("productNames", () => {
  it("returns the name of every product, in the same order", () => {
    expect(get("productNames")(makeProducts())).toEqual([
      "Notebook",
      "Backpack",
      "Pen",
      "Desk lamp",
      "Calculator",
    ]);
  });

  it("returns an empty list when there are no products", () => {
    expect(get("productNames")([])).toEqual([]);
  });

  it("leaves the original list alone", () => {
    const products = makeProducts();
    get("productNames")(products);
    expect(products).toEqual(makeProducts());
  });
});

describe("cheaperThan", () => {
  it("returns only the products under 100 EGP", () => {
    expect(get("cheaperThan")(makeProducts(), 100)).toEqual([
      { id: 1, name: "Notebook", price: 45, inStock: true },
      { id: 3, name: "Pen", price: 15, inStock: true },
    ]);
  });

  it("leaves out a product priced exactly at the limit", () => {
    const names = get("cheaperThan")(makeProducts(), 100).map((product) => product.name);
    expect(names).not.toContain("Calculator");
  });

  it("returns whole products, not just their names", () => {
    const [first] = get("cheaperThan")(makeProducts(), 100);
    expect(first).toHaveProperty("id");
    expect(first).toHaveProperty("price");
  });

  it("returns an empty list when nothing is cheap enough", () => {
    expect(get("cheaperThan")(makeProducts(), 10)).toEqual([]);
  });
});

describe("findById", () => {
  it("returns the one product with that id", () => {
    expect(get("findById")(makeProducts(), 4)).toEqual({
      id: 4,
      name: "Desk lamp",
      price: 180,
      inStock: true,
    });
  });

  it("returns a single product, not a list containing it", () => {
    expect(Array.isArray(get("findById")(makeProducts(), 4))).toBe(false);
  });

  it("returns undefined when no product has that id", () => {
    expect(get("findById")(makeProducts(), 999)).toBeUndefined();
  });

  it("returns undefined when the list is empty", () => {
    expect(get("findById")([], 1)).toBeUndefined();
  });
});

describe("totalPrice", () => {
  it("adds up every price", () => {
    expect(get("totalPrice")(makeProducts())).toBe(660);
  });

  it("returns 0 for an empty list", () => {
    expect(get("totalPrice")([])).toBe(0);
  });

  it("returns the single price when there is one product", () => {
    expect(get("totalPrice")([{ id: 1, name: "Pen", price: 15, inStock: true }])).toBe(15);
  });

  it("returns a number, not a string of joined prices", () => {
    expect(get("totalPrice")(makeProducts())).toBeTypeOf("number");
  });
});

describe("inStockNames", () => {
  it("exists, and is exported", () => {
    expect(get("inStockNames")).toBeTypeOf("function");
  });

  it("returns the names of the products that are in stock", () => {
    expect(get("inStockNames")(makeProducts())).toEqual(["Notebook", "Pen", "Desk lamp"]);
  });

  it("returns names, not product objects", () => {
    expect(get("inStockNames")(makeProducts()).every((name) => typeof name === "string")).toBe(true);
  });

  it("returns an empty list when nothing is in stock", () => {
    const soldOut = makeProducts().map((product) => ({ ...product, inStock: false }));
    expect(get("inStockNames")(soldOut)).toEqual([]);
  });
});
