// Tests for 10-css. You do not edit this file.
// Run them with: npm test 10
//
// These parse your stylesheet and look at the rules you wrote: which
// selectors exist and which properties they set. They cannot see the page,
// so they cannot tell you whether it LOOKS right — only you can, by opening
// it. Where a value has to be exact (display: flex) they check it; where the
// choice is yours (which colour) they only check that you made one.
import { describe, it, expect } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const here = path.dirname(fileURLToPath(import.meta.url));
const css = readFileSync(path.join(here, "exercise.css"), "utf8");
const { document } = new JSDOM(`<style>${css}</style>`).window;
const rules = [...document.styleSheets[0].cssRules];

function tidy(selector) {
  return selector.replace(/\s+/g, " ").trim().toLowerCase();
}

// All the declarations for one selector, merged — so splitting a rule in two
// is fine, and so is writing it all at once.
function styleFor(selector) {
  const wanted = tidy(selector);
  const matching = rules.filter((rule) => tidy(rule.selectorText ?? "") === wanted);
  const merged = {};
  for (const rule of matching) {
    for (const property of rule.style) {
      merged[property] = rule.style.getPropertyValue(property).trim();
    }
  }
  return { found: matching.length > 0, declarations: merged };
}

function expectRule(selector) {
  const { found, declarations } = styleFor(selector);
  expect(found, `No rule for \`${selector}\` in exercise.css.`).toBe(true);
  return declarations;
}

function expectSets(selector, property) {
  const declarations = expectRule(selector);
  expect(
    declarations[property],
    `Your \`${selector}\` rule does not set \`${property}\`.`
  ).toBeTruthy();
  return declarations[property];
}

function expectValue(selector, property, value) {
  const actual = expectSets(selector, property);
  expect(
    actual.toLowerCase(),
    `\`${selector}\` should set \`${property}: ${value}\`.`
  ).toBe(value);
}

// --- is the text actually readable? ----------------------------------------
// The tests above cannot see your page. These can see a little: they load the
// real exercise.html with your stylesheet applied, ask the browser engine what
// colour each piece of text ended up, and check there is enough contrast
// between the text and what is behind it.
//
// This is the WCAG contrast formula — the standard the web uses for "can a
// person actually read this". 4.5:1 is the official minimum for body text.
// These tests use 3:1, so only genuinely unreadable choices fail and taste is
// left to you.
const page = new JSDOM(
  readFileSync(path.join(here, "exercise.html"), "utf8").replace(
    '<link rel="stylesheet" href="exercise.css" />',
    `<style>${css}</style>`
  )
);

function channel(value) {
  const c = value / 255;
  return c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
}

function luminance(rgb) {
  const [r, g, b] = rgb;
  return 0.2126 * channel(r) + 0.7152 * channel(g) + 0.0722 * channel(b);
}

function parseRgb(value) {
  const match = /rgba?\(\s*(\d+)[,\s]+(\d+)[,\s]+(\d+)/.exec(value ?? "");
  return match ? [Number(match[1]), Number(match[2]), Number(match[3])] : null;
}

function contrast(front, back) {
  const a = luminance(front);
  const b = luminance(back);
  const [light, dark] = a > b ? [a, b] : [b, a];
  return (light + 0.05) / (dark + 0.05);
}

// Background colours are not inherited, so walk up until something sets one.
function backgroundBehind(element) {
  let node = element;
  while (node) {
    const value = page.window.getComputedStyle(node).backgroundColor;
    const rgb = parseRgb(value);
    if (rgb && !/rgba\([^)]*,\s*0\s*\)/.test(value)) return rgb;
    node = node.parentElement;
  }
  return null;
}

function readability(selector) {
  const element = page.window.document.querySelector(selector);
  if (!element) return null;
  const front = parseRgb(page.window.getComputedStyle(element).color);
  const back = backgroundBehind(element);
  if (!front || !back) return null;
  return { ratio: contrast(front, back), front, back };
}

function rgbText(rgb) {
  return `rgb(${rgb.join(", ")})`;
}

describe("is the text readable?", () => {
  it("the price can be read against what is behind it", () => {
    const result = readability(".price");
    if (!result) return; // nothing to judge yet; the rule tests cover that
    expect(
      result.ratio,
      `Your price text is ${rgbText(result.front)} on ${rgbText(result.back)}, ` +
        `a contrast of ${result.ratio.toFixed(2)}:1. Below 3:1 is very hard to ` +
        `read. Open the page and look at it: npm run open 10 exercise`
    ).toBeGreaterThan(3);
  });

  it("the body text can be read against the page background", () => {
    const result = readability("main p");
    if (!result) return;
    expect(
      result.ratio,
      `Your body text is ${rgbText(result.front)} on ${rgbText(result.back)}, ` +
        `a contrast of ${result.ratio.toFixed(2)}:1. Below 3:1 is very hard to read.`
    ).toBeGreaterThan(3);
  });
});

describe("the stylesheet itself", () => {
  it("has rules in it", () => {
    expect(rules.length, "exercise.css has no CSS rules yet.").toBeGreaterThan(0);
  });

  it("parses without breaking", () => {
    // A stray brace or a missing semicolon silently drops rules, so a count
    // well below what the exercise asks for usually means a syntax error.
    expect(rules.length).toBeGreaterThanOrEqual(7);
  });
});

describe("body", () => {
  it("sets a font", () => expectSets("body", "font-family"));
  it("sets a text colour", () => expectSets("body", "color"));
  it("sets a background colour", () => expectSets("body", "background-color"));
});

describe(".page", () => {
  it("limits how wide the page gets", () => expectSets(".page", "max-width"));
  it("sets a margin", () => expectSets(".page", "margin"));
});

describe("header", () => {
  it("is a flex container", () => expectValue("header", "display", "flex"));

  it("pushes the title and nav apart", () => {
    expectValue("header", "justify-content", "space-between");
  });

  it("lines them up vertically", () => {
    expectValue("header", "align-items", "center");
  });

  it("sets something of your own as well", () => {
    const declarations = expectRule("header");
    const required = ["display", "justify-content", "align-items"];
    const extra = Object.keys(declarations).filter((p) => !required.includes(p));
    expect(
      extra.length,
      "Add one more property of your choosing to the header rule."
    ).toBeGreaterThan(0);
  });
});

describe("nav a", () => {
  it("uses a descendant selector, not just `a`", () => {
    expectRule("nav a");
    const bareLink = rules.some((rule) => tidy(rule.selectorText ?? "") === "a");
    expect(
      bareLink,
      "Style `nav a`, not every `a` on the page — that is the point of the selector."
    ).toBe(false);
  });

  it("sets a colour", () => expectSets("nav a", "color"));
  it("sets text-decoration", () => expectSets("nav a", "text-decoration"));
});

describe(".card-list", () => {
  it("is a flex container", () => expectValue(".card-list", "display", "flex"));
  it("puts a gap between the cards", () => expectSets(".card-list", "gap"));
  it("lets the cards wrap onto a new line", () => {
    expectValue(".card-list", "flex-wrap", "wrap");
  });
});

describe(".card", () => {
  it("has padding inside it", () => expectSets(".card", "padding"));
  it("has rounded corners", () => expectSets(".card", "border-radius"));
  it("has its own background colour", () => {
    expectSets(".card", "background-color");
  });
});

describe(".price", () => {
  it("sets a colour", () => expectSets(".price", "color"));
  it("sets a font weight", () => expectSets(".price", "font-weight"));
});
