// Tests for 05-strings-json. You do not edit this file.
// Run them with: npm test 05
import { describe, it, expect } from "vitest";

// This file imports the whole exercise file at once, rather than naming each
// function, so that the one you have not written yet fails its own tests with
// a clear message instead of stopping the whole file.
import * as exercise from "./exercise.js";

function get(name) {
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

describe("shout", () => {
  it("trims the spaces and shouts", () => {
    expect(get("shout")("  notebook  ")).toBe("NOTEBOOK");
  });

  it("shouts a label that had no spaces to trim", () => {
    expect(get("shout")("Pen")).toBe("PEN");
  });

  it("leaves a label that is already shouting alone", () => {
    expect(get("shout")("PEN")).toBe("PEN");
  });
});

describe("initials", () => {
  it("turns Nour Gaser into NG", () => {
    expect(get("initials")("Nour Gaser")).toBe("NG");
  });

  it("upper-cases initials from a lowercase name", () => {
    expect(get("initials")("salma ahmed")).toBe("SA");
  });

  it("returns two letters, not the whole names", () => {
    expect(get("initials")("Ahmed Mansour")).toHaveLength(2);
  });
});

describe("toJson", () => {
  it("turns a product into JSON text", () => {
    expect(get("toJson")({ id: 1, name: "Notebook" })).toBe('{"id":1,"name":"Notebook"}');
  });

  it("returns a string, not an object", () => {
    expect(get("toJson")({ id: 1, name: "Notebook" })).toBeTypeOf("string");
  });

  it("produces text that can be parsed back", () => {
    const product = { id: 2, name: "Backpack", price: 320, inStock: false };
    expect(JSON.parse(get("toJson")(product))).toEqual(product);
  });
});

describe("displayName", () => {
  it("returns the name when there is one", () => {
    expect(get("displayName")({ name: "Salma" })).toBe("Salma");
  });

  it("falls back when the name is an empty string", () => {
    expect(get("displayName")({ name: "" })).toBe("Unknown student");
  });

  it("falls back when there is no name key at all", () => {
    expect(get("displayName")({})).toBe("Unknown student");
  });

  it("falls back when the name is null", () => {
    expect(get("displayName")({ name: null })).toBe("Unknown student");
  });
});

describe("summaryFromJson", () => {
  it("exists, and is exported", () => {
    expect(get("summaryFromJson")).toBeTypeOf("function");
  });

  it("summarizes a notebook from its JSON", () => {
    expect(get("summaryFromJson")('{ "name": "Notebook", "price": 45 }')).toBe(
      "Notebook costs 45 EGP"
    );
  });

  it("works for any product in the text", () => {
    expect(
      get("summaryFromJson")('{ "id": 2, "name": "Backpack", "price": 320 }')
    ).toBe("Backpack costs 320 EGP");
  });

  it("reads the text rather than always saying the same thing", () => {
    const first = get("summaryFromJson")('{ "name": "Pen", "price": 15 }');
    const second = get("summaryFromJson")('{ "name": "Desk lamp", "price": 180 }');
    expect(first).not.toBe(second);
  });
});
