// Tests for 12-dom-write. You do not edit this file.
// Run them with: npm test 12
import { describe, it, expect, beforeEach } from "vitest";
import { readFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { JSDOM } from "jsdom";

const here = path.dirname(fileURLToPath(import.meta.url));
const html = readFileSync(path.join(here, "exercise.html"), "utf8");

const dom = new JSDOM(html);
globalThis.window = dom.window;
globalThis.document = dom.window.document;
const { document } = dom.window;
const pristine = document.body.innerHTML;

let exercise = null;
let loadError = null;
try {
  exercise = await import("./exercise.js");
} catch (error) {
  loadError = error;
}

function get(name) {
  if (loadError) {
    throw new Error(`exercise.js could not be loaded.\n        ${loadError.message}`);
  }
  const fn = exercise[name];
  if (typeof fn !== "function") {
    throw new Error(
      `exercise.js does not export a function called "${name}" yet.\n` +
        `        Write it, and check that the line starts with the word "export".`
    );
  }
  return fn;
}

const cards = () => document.querySelectorAll("#list .card");
const names = () =>
  Array.from(document.querySelectorAll("#list .card h3")).map((h) => h.textContent);

beforeEach(() => {
  document.body.innerHTML = pristine;
});

describe("addProduct", () => {
  it("adds a card to the list", () => {
    get("addProduct")("Pen", 15);
    expect(cards()).toHaveLength(1);
  });

  it("puts the name in an h3", () => {
    get("addProduct")("Pen", 15);
    expect(document.querySelector("#list .card h3").textContent).toBe("Pen");
  });

  it("puts the price, followed by EGP, in a p with the class price", () => {
    get("addProduct")("Pen", 15);
    expect(document.querySelector("#list .card p.price").textContent).toBe("15 EGP");
  });

  it("makes the card an li with the class card", () => {
    get("addProduct")("Pen", 15);
    const card = document.querySelector("#list .card");
    expect(card.tagName).toBe("LI");
    expect(card.classList.contains("card")).toBe(true);
  });

  it("adds each new card after the ones already there", () => {
    get("addProduct")("Pen", 15);
    get("addProduct")("Notebook", 45);
    get("addProduct")("Backpack", 320);
    expect(names()).toEqual(["Pen", "Notebook", "Backpack"]);
  });
});

describe("removeProduct", () => {
  it("removes the card with that name", () => {
    get("addProduct")("Pen", 15);
    get("addProduct")("Notebook", 45);
    get("removeProduct")("Pen");
    expect(names()).toEqual(["Notebook"]);
  });

  it("leaves the others alone", () => {
    get("addProduct")("Pen", 15);
    get("addProduct")("Notebook", 45);
    get("addProduct")("Backpack", 320);
    get("removeProduct")("Notebook");
    expect(names()).toEqual(["Pen", "Backpack"]);
  });

  it("does nothing when there is no card with that name", () => {
    get("addProduct")("Pen", 15);
    expect(() => get("removeProduct")("Nothing")).not.toThrow();
    expect(cards()).toHaveLength(1);
  });
});

describe("markSoldOut", () => {
  it("adds the sold-out class to that card", () => {
    get("addProduct")("Pen", 15);
    get("markSoldOut")("Pen");
    expect(document.querySelector("#list .card").classList.contains("sold-out")).toBe(true);
  });

  it("keeps the card on the page", () => {
    get("addProduct")("Pen", 15);
    get("markSoldOut")("Pen");
    expect(cards()).toHaveLength(1);
  });

  it("marks only the card asked for", () => {
    get("addProduct")("Pen", 15);
    get("addProduct")("Notebook", 45);
    get("markSoldOut")("Notebook");
    const [pen, notebook] = document.querySelectorAll("#list .card");
    expect(pen.classList.contains("sold-out")).toBe(false);
    expect(notebook.classList.contains("sold-out")).toBe(true);
  });

  it("does nothing when there is no card with that name", () => {
    expect(() => get("markSoldOut")("Nothing")).not.toThrow();
  });
});

describe("clearProducts", () => {
  it("empties the list", () => {
    get("addProduct")("Pen", 15);
    get("addProduct")("Notebook", 45);
    get("clearProducts")();
    expect(cards()).toHaveLength(0);
  });

  it("works on a list that is already empty", () => {
    expect(() => get("clearProducts")()).not.toThrow();
    expect(cards()).toHaveLength(0);
  });

  it("leaves the list element itself on the page", () => {
    get("addProduct")("Pen", 15);
    get("clearProducts")();
    expect(document.querySelector("#list")).not.toBeNull();
  });
});

describe("wireButtons", () => {
  it("exists, and is exported", () => {
    expect(get("wireButtons")).toBeTypeOf("function");
  });

  it("makes the add button add a Notebook at 45 EGP", () => {
    get("wireButtons")();
    document.querySelector("#add").click();
    expect(names()).toEqual(["Notebook"]);
    expect(document.querySelector("#list .card p.price").textContent).toBe("45 EGP");
  });

  it("adds another one on every click", () => {
    get("wireButtons")();
    const add = document.querySelector("#add");
    add.click();
    add.click();
    add.click();
    expect(cards()).toHaveLength(3);
  });

  it("makes the reset button empty the list", () => {
    get("wireButtons")();
    document.querySelector("#add").click();
    document.querySelector("#add").click();
    document.querySelector("#reset").click();
    expect(cards()).toHaveLength(0);
  });

  it("listens for clicks rather than doing the work immediately", () => {
    // Wiring on its own must not add anything.
    get("wireButtons")();
    expect(cards()).toHaveLength(0);
  });
});
